export const WEBSOCKET_MODULE = 'websocket';

export const SOCKET_ONOPEN = 'SOCKET_ONOPEN';
export const SOCKET_ONCLOSE = 'SOCKET_ONCLOSE';
export const SOCKET_ONERROR = 'SOCKET_ONERROR';
export const SOCKET_ONMESSAGE = 'SOCKET_ONMESSAGE';
export const SOCKET_RECONNECT = 'SOCKET_RECONNECT';
export const SOCKET_RECONNECT_ERROR = 'SOCKET_RECONNECT_ERROR';

export const SOCKET_IS_CONNECTED = 'SOCKET_IS_CONNECTED';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';

export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_OBJ_MESSAGE = 'SOCKET_SEND_OBJ_MESSAGE';

export const MESSAGE_TYPES = {
	KEEPALIVE: 'keepalive',
	CONSOLE: 'console',
	IMMUDB: 'immudb',
};
